/**
 * Permission code constants mirrored from prisma/seed/lib/rbac-catalog.ts.
 * Codes only — grant computation and seeding remain on the server.
 */

export const PERMISSION_CODES = [
  "user.view",
  "user.manage",
  "user.delete",
  "user.reset_password",
  "api_key.manage",
  "user.impersonate",
  "permission.view",
  "customer.view",
  "customer.create",
  "customer.update",
  "customer.merge",
  "customer.identifier.unmask",
  "lead.view",
  "lead.create",
  "lead.update",
  "lead.call_feedback.record",
  "saved_view.manage",
  "lead.reassign",
  "tag.manage",
  "lead.import",
  "custom_field.manage",
  "lead_center.view",
  "lead_center.manage",
  "lead_center.import",
  "integration.view",
  "integration.manage",
  "follow_up.view",
  "follow_up.create",
  "follow_up.complete",
  "follow_up.reassign",
  "campaign.view",
  "campaign.assign",
  "campaign.manage",
  "bank.view",
  "bank.manage",
  "commission_policy.publish",
  "loan_product.view",
  "loan_product.manage",
  "loan_application.view",
  "loan_application.create",
  "eligibility.compute",
  "loan_offer.manage",
  "loan_application.decide",
  "loan_account.view",
  "loan_account.manage",
  "foreclosure.manage",
  "disbursement.view",
  "disbursement.record",
  "commission.view",
  "disbursement.reconcile",
  "commission.reconcile",
  "call.initiate",
  "call.view",
  "call.monitor",
  "agent_session.manage",
  "call.recording.access",
  "dialer_campaign.manage",
  "call.update",
  "call.note.manage",
  "call.recording.log",
  "call.outcome.manage",
  "agent_session.self",
  "telephony.dashboard.view",
  "document.view",
  "document.upload",
  "document.verify",
  "document.share",
  "document.category.manage",
  "documents.dashboard.view",
  "retention_policy.manage",
  "legal_hold.manage",
  "notification.view",
  "notification.send",
  "broadcast.manage",
  "notification.template.manage",
  "notification.preference.manage",
  "notification.queue.process",
  "notifications.dashboard.view",
  "provider.manage",
  "report.view",
  "report.manage",
  "dashboard.manage",
  "export.create",
  "analytics_dataset.manage",
  "audit.view",
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];

export const PERMISSION_CODE_SET: ReadonlySet<string> = new Set(PERMISSION_CODES);

export function isPermissionCode(value: string): value is PermissionCode {
  return PERMISSION_CODE_SET.has(value);
}
