plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.mudraxcapitals.crm'
version = '1.0.0'

android {
  namespace "expo.modules.mudraxcalllog"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation "androidx.documentfile:documentfile:1.0.1"
}
